/*
 *  com_android_porting_common_facebook_FacebookBridge.cpp
 *
 *  Created on: 2013-7-19
 *  Author: liujian
 */
 
 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_jni_facebook_FacebookBridge */

#ifndef _Included_com_common_android_facebook_FacebookBridge
#define _Included_com_common_android_facebook_FacebookBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.android.porting.common.facebook_FacebookBridge
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_android_porting_common_facebook_FacebookBridge
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeFinalize
  (JNIEnv *, jobject);

/*
 * Class:     com_android_porting_common_facebook_FacebookBridge
 * Method:    nativeOnPostStatus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeOnPostStatus
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_android_porting_common_facebook_FacebookBridge
 * Method:    nativeOnPostPhoto
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeOnPostPhoto
  (JNIEnv *, jobject, jint, jboolean);
  
/*
 * Class:     com_android_porting_common_facebook_FacebookBridge
 * Method:    nativeOnPostRichContent
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeOnPostRichContent
  (JNIEnv *, jobject, jint, jboolean);
  
  /*
 * Class:     com_android_porting_common_facebook_FacebookBridge
 * Method:    nativeOnPostTimeOut
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_common_android_facebook_FacebookBridge_nativeOnPostTimeOut
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
