/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_STInstagramFunction */

#ifndef _Included_com_common_android_jni_STInstagramFunction
#define _Included_com_common_android_jni_STInstagramFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_STInstagramFunction
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STInstagramFunction_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_STSystemFunction
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_STInstagramFunction_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
